enum declaration for StrKind, ExprKind
Reduce header include, but violate `pedantic`.

CIで失敗：

```
cc -ansi -std=c11 -pedantic -MMD -Wall -Wextra -Werror -Wold-style-definition -Wno-missing-field-initializers -Wno-empty-body -D_DEFAULT_SOURCE -O2 -g3 -Isrc/util -DXCC_TARGET_ARCH=XCC_ARCH_X64 -Isrc/cc/frontend -c -o obj/initializer.o src/cc/frontend/initializer.c
In file included from src/cc/frontend/expr.c:2:
src/cc/frontend/expr.h:22:68: error: ISO C forbids forward references to ‘enum’ types [-Werror=pedantic]
   22 | Expr *string_expr(const Token *token, char *str, ssize_t len, enum StrKind kind);
      |                                                                    ^~~~~~~
src/cc/frontend/expr.h:32:29: error: ISO C forbids forward references to ‘enum’ types [-Werror=pedantic]
   32 | Expr *new_expr_num_bop(enum ExprKind kind, const Token *tok, Expr *lhs, Expr *rhs);
      |                             ^~~~~~~~
src/cc/frontend/expr.h:33:29: error: ISO C forbids forward references to ‘enum’ types [-Werror=pedantic]
   33 | Expr *new_expr_int_bop(enum ExprKind kind, const Token *tok, Expr *lhs, Expr *rhs);
      |                             ^~~~~~~~
src/cc/frontend/expr.h:34:28: error: ISO C forbids forward references to ‘enum’ types [-Werror=pedantic]
   34 | Expr *new_expr_addsub(enum ExprKind kind, const Token *tok, Expr *lhs, Expr *rhs);
      |                            ^~~~~~~~
src/cc/frontend/expr.h:41:22: error: ISO C forbids forward references to ‘enum’ types [-Werror=pedantic]
   41 | Expr *incdec_of(enum ExprKind kind, Expr *target, const Token *tok);
      |                      ^~~~~~~~
src/cc/frontend/expr.h:42:25: error: ISO C forbids forward references to ‘enum’ types [-Werror=pedantic]
   42 | Expr *new_expr_cmp(enum ExprKind kind, const Token *tok, Expr *lhs, Expr *rhs);
      |                         ^~~~~~~~
```