weak_alias をサポートする
  * アセンブラで `.set` に対応する

```asm
        .weak   foobar
        .set    foobar,sub
```

Darwinでは`alias`はサポートされてない：

```sh
$ gcc -S -o- examples/weak_alias.c
examples/weak_alias.c:9:1: error: aliases are not supported on darwin
    9 | weak_alias(sub, foobar);
      | ^
examples/weak_alias.c:2:53: note: expanded from macro 'weak_alias'
    2 |   extern __typeof(old) new __attribute__((__weak__, __alias__(#old)))
      |                                                     ^
1 error generated.
```

LLVM: "clang claims weak aliases are not supported on Darwin but only when using __attribute__, works fine with pragma"

`alias` を`VarInfo`に格納。
またweakフラグをセット。

# Conflicts:
#	src/as/emit_elf.c
#	src/as/parse_asm.c

# Conflicts:
#	src/cc/frontend/parser.c